import dotenv from 'dotenv';
dotenv.config();

export const config = {
  port: parseInt(process.env.PORT || '3001', 10),
  jwtSecret: process.env.JWT_SECRET || 'dev-secret',
  corsOrigin: process.env.CORS_ORIGIN || 'http://localhost:5173',
  db: {
    server: process.env.DB_SERVER || 'WINDOWTRAGIC\\SQLEXPRESS',
    database: process.env.DB_NAME || 'ViolenceManga',
    user: process.env.DB_USER || undefined,
    password: process.env.DB_PASSWORD || undefined,
    trusted: process.env.DB_TRUSTED !== 'false',
  },
};

export const defaultState = {
  profile: {
    name: 'Гость',
    avatar: 'G',
    avatarUrl: '',
    bio: '',
    xp: 0,
    level: 1,
    joinedAt: Date.now(),
  },
  settings: {
    theme: 'dark',
    palette: 'violet',
    animations: true,
    transitionSpeed: 'normal',
    effectsGlow: true,
    effectsBlur: true,
    effectsOrbs: true,
    effectsCardHover: true,
    readingMode: 'vertical',
    fitWidth: true,
    language: 'ru',
    autoTranslate: true,
    autoBookmark: true,
    showNsfw: false,
    chapterSort: 'desc',
    compactSidebar: false,
    pageSpread: false,
    imageProxy: true,
    prefetchEnabled: true,
    prefetchAhead: 3,
    uiLanguage: 'ru',
    autoScrollSpeed: 0,
    iosBoldFont: false,
  },
  readingLog: {},
  genreStats: {},
  favorites: [],
  history: [],
  readChapters: [],
  bookmarks: {},
  lists: { reading: [], plan: [], completed: [], dropped: [] },
  listMeta: {},
  stats: {
    chaptersRead: 0,
    pagesRead: 0,
    mangaOpened: 0,
    searchCount: 0,
    favoritesCount: 0,
    totalReadTime: 0,
  },
  achievements: {},
  notifications: [],
};
